version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  init:
    resource_class: small
    working_directory: ~/code
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Export BUILD_ID
          command: echo $CIRCLE_BUILD_NUM | tee ~/code/build-id
      - persist_to_workspace:
          root: ~/
          paths:
            - code
            - .ssh

  build:
    resource_class: small
    working_directory: ~/code
    docker:
      - image: cimg/python:3.10.2
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Parallel run
          command: |
            echo "Current directory: $(pwd)" # /home/circleci/code
            mkdir -p ~/output
            echo "Hello from ${CIRCLE_NODE_INDEX}/${CIRCLE_NODE_TOTAL}" > ~/output/report-$CIRCLE_NODE_INDEX.txt
            find ~/output -type f
      - store_artifacts:
          path: ~/output
          destination: artifact-file
      - persist_to_workspace:
          root: ~/
          paths:
            - output

  report:
    resource_class: small
    working_directory: ~/code
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Parallel run
          command: |
            # Output:
            # /home/circleci/output/report-0.txt content: Hello from 0/4
            # /home/circleci/output/report-1.txt content: Hello from 1/4
            # /home/circleci/output/report-2.txt content: Hello from 2/4
            # /home/circleci/output/report-3.txt content: Hello from 3/4
            # https://app.circleci.com/pipelines/github/pgreze/circleci-howto/11/workflows/cfd59ef1-e30e-49e1-8874-83d7368c7d02/jobs/27
            for file in ~/output/*; do
              echo "$file content: $(cat $file)"
            done

workflows:
  deploy:
    jobs:
      - init
      - build:
          requires: [init]
      - report:
          requires: [build]
