version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  init:
    resource_class: small
    working_directory: ~/code
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Export BUILD_ID
          command: echo $CIRCLE_BUILD_NUM | tee ~/code/build-id
      - persist_to_workspace:
          root: ~/
          paths:
            - code
            - .ssh

  build:
    resource_class: small
    working_directory: ~/code
    docker:
      - image: cimg/python:3.10.2
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Parallel run
          command: |
            echo "Current directory: $(pwd)"
            mkdir -p "~/output"
            echo "Hello from $CIRCLE_NODE_INDEX/$CIRCLE_NODE_TOTAL" > "~/output/report-$CIRCLE_NODE_INDEX.txt"
            find "~/output"
      - store_artifacts:
          path: ~/output
          destination: artifact-file
      - persist_to_workspace:
          root: ~/
          paths:
            - output

  report:
    resource_class: small
    working_directory: ~/code
    docker:
      - image: cimg/python:3.10.2
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Parallel run
          command: |
            for file in output/*; do
              echo "$file content: $(cat $file)"
            done

workflows:
  deploy:
    jobs:
      - init
      - build:
          requires: [init]
      - report:
          requires: [build]
